Repository Yashsharma1911/Golang-tutorial, pull requests merged in 2023-07, with the labels that each got.

#26 [Doc] Added template for contributors bot
  README.md
Labels: enhancement

#23 Created README.md file for Loops in Golang.
  Loops/README.md
Labels: documentation

#18 Created README.md for maps
  Maps/README.md
Labels: documentation

#54 Created a basic cli ticket booking app tutorial and arranged Projects dir
  Projects/01 Beginner Projects/bookingapp/README.md
  Projects/01 Beginner Projects/bookingapp/main.go
  Projects/02 Intermediate Projects/CRUD-server/README.md
  Projects/02 Intermediate Projects/CRUD-server/create_account.go
  Projects/02 Intermediate Projects/CRUD-server/delete_account.go
  Projects/02 Intermediate Projects/CRUD-server/get_accounts.go
  Projects/02 Intermediate Projects/CRUD-server/main.go
  Projects/02 Intermediate Projects/CRUD-server/update_account.go
  Projects/02 Intermediate Projects/basic-go-server/main.go
  Projects/02 Intermediate Projects/basic-go-server/static/index.html
Labels: language/golang
